name: SRL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - array-record==0.6.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==24.3.0
    - av==12.3.0
    - backports-tarfile==1.2.0
    - black==22.12.0
    - braceexpand==0.1.7
    - build==1.2.2.post1
    - cachecontrol==0.14.3
    - certifi==2024.12.14
    - cffi==1.17.1
    - cfgv==3.4.0
    - charset-normalizer==3.4.1
    - cleo==2.1.0
    - click==8.1.8
    - contourpy==1.3.1
    - crashtest==0.4.1
    - cryptography==45.0.3
    - cycler==0.12.1
    - decorator==4.4.2
    - distlib==0.3.9
    - dm-tree==0.1.8
    - docstring-parser==0.16
    - dulwich==0.22.8
    - einops==0.6.1
    - etils==1.11.0
    - exceptiongroup==1.2.2
    - fastjsonschema==2.21.1
    - filelock==3.16.1
    - findpython==0.6.3
    - flatbuffers==24.12.23
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.69.0
    - h11==0.16.0
    - h5py==3.12.1
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.27.1
    - identify==2.6.5
    - idna==3.10
    - imageio==2.36.1
    - imageio-ffmpeg==0.5.1
    - immutabledict==4.2.1
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - iniconfig==2.0.0
    - installer==0.7.0
    - isort==5.13.2
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.1.0
    - jeepney==0.9.0
    - keras==3.8.0
    - keyring==25.6.0
    - kiwisolver==1.4.8
    - libclang==18.1.1
    - lightning-utilities==0.11.9
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - ml-dtypes==0.4.1
    - more-itertools==10.7.0
    - moviepy==1.0.3
    - msgpack==1.1.0
    - multidict==6.1.0
    - mypy-extensions==1.0.0
    - namex==0.0.8
    - nodeenv==1.9.1
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - omegaconf==2.3.0
    - opt-einsum==3.4.0
    - optree==0.13.1
    - packaging==24.2
    - pathspec==0.12.1
    - pbs-installer==2025.5.17
    - pillow==11.1.0
    - pkginfo==1.12.1.2
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - poetry==2.1.3
    - poetry-core==2.1.3
    - pre-commit==2.21.0
    - proglog==0.1.10
    - promise==2.3
    - propcache==0.2.1
    - protobuf==3.20.3
    - psutil==6.1.1
    - pyarrow==18.1.0
    - pycocotools==2.0.8
    - pycparser==2.22
    - pygments==2.19.1
    - pyparsing==3.2.1
    - pyproject-hooks==1.2.0
    - pytest==7.4.4
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==1.9.5
    - pyyaml==6.0.2
    - rapidfuzz==3.13.0
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - ruff==0.0.292
    - safetensors==0.5.2
    - scipy==1.15.1
    - secretstorage==3.3.3
    - setuptools==75.8.0
    - shellingham==1.5.4
    - simple-parsing==0.1.6
    - six==1.17.0
    - slotcontrast==0.1.0
    - sniffio==1.3.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow-cpu==2.18.0
    - tensorflow-datasets==4.9.7
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-metadata==1.16.1
    - termcolor==2.5.0
    - timm==0.9.16
    - toml==0.10.2
    - tomli==2.2.1
    - tomlkit==0.13.2
    - torch==1.13.1
    - torchmetrics==1.5.2
    - torchvision==0.14.1
    - tqdm==4.67.1
    - trove-classifiers==2025.5.9.12
    - typing-extensions==4.12.2
    - urllib3==2.3.0
    - virtualenv==20.28.1
    - webdataset==0.2.100
    - werkzeug==3.1.3
    - wrapt==1.17.1
    - yarl==1.18.3
    - zipp==3.21.0
    - zstandard==0.23.0
